# -*- coding: utf-8 -*-
"""p.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GtMBbg95hykiLpOeQ6_oYMNCjGVJPUQ
"""

import pandas as pd
import numpy as np
import streamlit as st
import time
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv("/content/urban_climate.csv")

data

"""What are the first few rows of the dataset?"""

data.head()

"""What columns does the dataset have?"""

data.columns.tolist()

"""What are the basic statistics of the dataset?"""

data.describe()

"""Are there any missing values?"""

data.isnull().sum()

"""How many unique years are in the data?"""

data['year'].nunique()

data2 = pd.read_csv("/content/urban_climate.csv")

data2

data3 = pd.read_csv("/content/ice_core_co2.csv")

data3

"""What is the average temperature anomaly by year?"""

data.groupby('year')['temperature_celsius'].mean()

"""Which year recorded the highest CO₂ level?"""

data3.loc[data3['co2_ppm'].idxmax(), ['calendar_year', 'co2_ppm']]

"""Plot temperature anomaly over time?"""

data.groupby('year')['temperature_celsius'].mean().rolling(10).mean().plot(figsize=(8,5), color='crimson', lw=2, title=' Global Temp Anomaly (10-Year Avg)')

"""Plot CO₂ concentration over years?"""

x=data3['calendar_year']; y=data3['co2_ppm']; plt.scatter(x,y,c=y,cmap='plasma'); plt.title('CO₂ Levels Over Time'); plt.xlabel('Year'); plt.ylabel('CO₂ (ppm)'); plt.colorbar(label='CO₂ Level'); plt.show()

data4 = pd.read_csv("/content/combined_dataset.csv")

data4

"""Compare temperature vs CO₂ trend?"""

plt.scatter(data4['co2_ppm'], data4['temperature_celsius']); plt.title("CO₂ vs Temperature"); plt.show()

"""Sea level rise trend?

"""

plt.plot(data3['calendar_year'], data3['co2_ppm'], color='blue'); plt.title("CO2 Concentration Over Time (from Ice Core Data)"); plt.xlabel("Year"); plt.ylabel("CO2 (ppm)"); plt.show()

"""Multi-line plot for all three indicators?"""

data4.plot(x='year', y=['temperature_celsius','co2_ppm','sea_level_mm'], title="Climate Change Indicators"); plt.show()

"""Render ASCII frame for a specific year?"""

climate_data_2000 = data.loc[data['year']==2000].iloc[0]
temp_2000 = climate_data_2000['temperature_celsius']
co2_data_2000 = data3.loc[data3['calendar_year']==2000]
if not co2_data_2000.empty:
    co2_2000 = co2_data_2000.iloc[0]['co2_ppm']
else:
    co2_2000 = 0
    print("Note: No CO2 data found for the year 2000 in data3. Using a placeholder for CO2.")
sea_level_2000 = 0
print("Note: Sea level rise data is not available in the current datasets. Using a placeholder for sea level.")
def render_ascii(temp, co2, sea):
    ice = max(0, 8 - int((co2 - 280) / 20))
    forest = max(0, 8 - int(temp / 5))
    ocean = 8 + int(sea / 2)
    frame = f"""
   {'^'*ice}       (ice)
  {'#'*forest}{'.'*(8-forest)}   (land)
  {'~'*ocean}   (ocean)
    """
    return frame
ascii_frame_2000 = render_ascii(temp_2000, co2_2000, sea_level_2000)
print(f"ASCII Climate Storyboard for Year 2000:")
print(ascii_frame_2000)

"""Loop through years to animate ASCII story?"""

import time, os
from IPython.display import clear_output
years = sorted(data['year'].unique())

print("Starting ASCII Climate Storyboard Animation (using available data)...")
print("Note: Sea level rise data is not available and will be represented by a placeholder.")
print("Note: CO2 data is from ice core samples and may not align perfectly year-to-year with urban climate data.")

for year in years:
    climate_data_year = data.loc[data['year'] == year]

    if not climate_data_year.empty:
        temp_year = climate_data_year.iloc[0]['temperature_celsius']
    else:
        temp_year = 0
        print(f"Warning: No urban climate data found for year {year}. Using placeholder temperature.")
    co2_data_year = data3.loc[data3['calendar_year'] == year]
    if not co2_data_year.empty:
        co2_year = co2_data_year.iloc[0]['co2_ppm']
    else:
        co2_year = 0
    sea_level_year = 0
    clear_output(wait=True)
    print(f"\nYear {year}\n")
    print(render_ascii(temp_year, co2_year, sea_level_year))

    time.sleep(0.5)

print("\nAnimation finished.")

"""Compute linear trend of temperature anomaly?"""

np.polyfit(data['year'], data['temperature_celsius'], 1)

"""Predict next decade’s CO₂ level (simple linear extrapolation)?"""

m,b=np.polyfit(data3['calendar_year'],data3['co2_ppm'],1); print(b+m*2030)

"""Find periods of rapid warming (Δtemp > 0.1°C/year)?"""

data4[data4['temperature_celsius'].diff()>0.1]

"""When did temperature rise start accelerating sharply?"""

data.loc[data['temperature_celsius'].diff().abs().idxmax(), ['year','temperature_celsius']]

"""How tightly are CO₂ levels and temperature linked across time?"""

round(data4['co2_ppm'].corr(data4['temperature_celsius']), 3)

"""Which years show unusually high jumps in all 3 variables simultaneously?"""

data4[(data4['temperature_celsius'].diff()>0.1)&(data4['co2_ppm'].diff()>2)]

"""Which decade was most stable (lowest change rate)?"""

data.groupby(data['year']//10*10)['temperature_celsius'].std().idxmin()

"""How many mm of sea-level rise occur per °C of warming?"""

(data['sea_level_mm'].max()-data['sea_level_mm'].min())/(data['temp_anomaly'].max()-data['temp_anomaly'].min())

"""How much temperature change per ppm of CO₂ increase?"""

(data4['temperature_celsius'].max()-data4['temperature_celsius'].min())/(data4['co2_ppm'].max()-data4['co2_ppm'].min())

"""Visualize acceleration of warming (2nd derivative)?"""

data['temperature_celsius'].diff().diff().plot(title="Acceleration of Global Warming")

"""In which decade did warming trend shift direction?"""

data4['trend']=data4['temperature_celsius'].rolling(5).mean().diff(); data4.loc[data4['trend'].abs().idxmax(), 'year']

"""Show years with record-breaking warming events?"""

data4[data4['temperature_celsius']==data4['temperature_celsius'].cummax()]

"""Is warming accelerating faster than CO₂ growth?"""

(data4['temperature_celsius'].pct_change().mean()) > (data4['co2_ppm'].pct_change().mean())

"""What might the global temp anomaly be by 2035?"""

cleaned_data = data4.dropna(subset=['year', 'temperature_celsius'])

m,b=np.polyfit(cleaned_data['year'],cleaned_data['temperature_celsius'],1); round(m*2035+b,2)

"""How much ice has theoretically “melted” since pre-industrial (proxy)?"""

(data4['temperature_celsius']-data4['temperature_celsius'].min()).sum()

"""In how many years did all three indicators rise together (Earth’s “cry years”)?"""

len(data4[(data4['temperature_celsius'].diff()>0)&(data4['co2_ppm'].diff()>0)&(data4['sea_level_mm'].diff()>0)])

"""Create a single metric blending all indicators (0–100)?"""

data4['mood']=((data4['temperature_celsius'].rank()+data4['co2_ppm'].rank()+data4['sea_level_mm'].rank())/3)/len(data4)*100; data4[['year','mood']].tail()

"""Print a visual mood bar for each decade?"""

for _,r in data4.iterrows(): print(f"{r.year}: {'█'*int(r.temperature_celsius*10)} ({round(r.temperature_celsius,2)}°C)")

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

co2 = pd.read_csv('/content/co2_emissions.csv')
urban = pd.read_csv('/content/urban_climate.csv')
ice = pd.read_csv('/content/ice_core_co2.csv')

combined_df = pd.concat([co2, urban, ice], ignore_index=True)

combined_df.to_csv('combined_dataset.csv', index=False)

print(" Combined dataset shape:", combined_df.shape)
print(" Saved as combined_dataset.csv")

"""Linear Regression(Quantify how fast Earth is warming, Calculate slope → °C change per decade.)"""

from sklearn.linear_model import LinearRegression
import numpy as np

# Remove rows with NaN in 'year' or 'temperature_celsius' before fitting
cleaned_data = data4.dropna(subset=['year', 'temperature_celsius'])

X = cleaned_data[['year']]; y = cleaned_data['temperature_celsius']
model = LinearRegression().fit(X, y)
print(f"Trend: {model.coef_[0]*10:.3f}°C per decade")

"""Z-score or Isolation Forest(Automatically detect abnormal years — climate “shock” events.)"""

from sklearn.ensemble import IsolationForest
outliers = IsolationForest(contamination=0.05).fit_predict(data4[['temperature_celsius','co2_ppm','sea_level_mm']])
data4['outlier'] = outliers

"""Correlation matrix + heatmap(Quantify how tightly temperature, CO₂, and sea level move together.)"""

sns.heatmap(data4[['temperature_celsius','co2_ppm','sea_level_mm']].corr(), annot=True, cmap='coolwarm')

"""Ruptures (change-point detection)Detect the year when global climate trend sharply changed (e.g., industrial era)."""

import ruptures as rpt
signal = data4['temperature_celsius'].values
model = rpt.Pelt(model="rbf").fit(signal)
breaks = model.predict(pen=10)
print("Detected climate regime shifts:", [data4['year'].iloc[b] for b in breaks])

"""ARIMA or Prophet(Extend your ASCII animation into the future)"""

from statsmodels.tsa.arima.model import ARIMA
model = ARIMA(data4['temperature_celsius'], order=(1,1,1)).fit()
future = model.forecast(steps=50)

import os, time

def ascii_frame(year, temp):
    ice = '^' * max(1, 20 - int(temp * 3))
    ocean = '~' * min(25, 10 + int(temp * 5))
    land = "#######   (land)"

    os.system('cls' if os.name=='nt' else 'clear')
    print(f"ASCII Climate Storyboard: Year {year}")
    print(f"Temperature anomaly: {temp:.2f}°C\n")
    print(f"   {ice}   (ice)")
    print(f"  {land}")
    print(f"  {ocean}   (ocean)")

cleaned_data4 = data4.dropna(subset=['year', 'temperature_celsius'])
for _, row in cleaned_data4.iterrows():
    ascii_frame(int(row['year']), row['temperature_celsius'])
    time.sleep(0.3)

# Group by year and take the mean of numerical columns to handle duplicate years
data4_yearly = data4.groupby('year').mean(numeric_only=True)

# Reindex to include all years in the range and interpolate missing values
data4 = data4_yearly.reindex(range(int(data4_yearly.index.min()), int(data4_yearly.index.max())+1)).interpolate().reset_index()

pip install streamlit pandas matplotlib numpy

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

data4 = pd.read_csv("/content/combined_dataset.csv")

st.title(" ASCII Climate Storyboard")
year = st.slider("Select Year", int(data4['year'].min()), int(data4['year'].max()), 2000)

row = data4[data4['year'] == year].iloc[0]
temp, co2 = row['temperature_celsius'], row['co2_ppm']

ice = '^' * max(1, 20 - int(temp*2))
# Sea level data is not available, represent with a placeholder
ocean = "~"*8 # Placeholder
st.text(f"Year {year}\n{ice} (ice)\n#######. (land)\n{ocean} (ocean)")

fig, ax = plt.subplots()
data4.groupby('year')['temperature_celsius'].mean().plot(ax=ax, color='tomato')
plt.title("Global Temperature Anomaly Over Time")
st.pyplot(fig)